#!/bin/bash

#if [ $# == 0 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
#    echo "Usage: $0 FILE [FILE [...]]"
#    echo Counts lines per C function
#    exit 1
#fi

AWK_PROGRAM='/^[A-Za-z].*$/ {start=1; count=0; name=$0;} start == 1 && /{$/ {start = 0; middle=1} middle==1 { count+=1  } /^}$/ {middle=0; print count-2 ":", FILENAME ":", name}' 
if [ $# = 0 ]; then
    find . -name '[^.]*.cc' -o -name '[^.]*.c' -o -name '[^.]*.h' | xargs awk "$AWK_PROGRAM" | sort -n
else
    awk  "$AWK_PROGRAM" "$@" | sort -n
fi
