#!/bin/bash

AWK_PROGRAM='current_file != FILENAME { print current_file ":" num, max_length; current_file = FILENAME; max_length=0;} length > max_length {max_length = length($0); num=FNR;}' 

if [ $# = 0 ]; then
    find . -name '*.c' -o -name '*.h' | xargs awk "$AWK_PROGRAM" | sort -k2 -n | awk '$2 > 80'
else
    awk "$AWK_PROGRAM" "$@" | sort -k2 -n | awk '$2 > 80'
fi
