#!/bin/bash

user1=$1
user2=$2

for user1_pokemon in `cat Users/${user1}/${user1}.txt | cut -d ":" -f 1`; do
	user1_pokemon_types=`get_pokemon_attribute $user1_pokemon "Type"`
	for matched_user2_pokemon in `find_user_with_pokemons $user2 W $user1_pokemon_types`; do
		echo "$user1 : $user1_pokemon $user2 : $matched_user2_pokemon"
	done
done | sort -r -k 2,4 | head -n 1
