#!/bin/bash

attribute=$1
if [ "$attribute" == "T" ]; then
	attribute="Type"
else
	attribute="Weakness"
fi

values=`echo $@ | cut -d " " -f 2-`

for pokemon_name in `get_all_pokemon_names | sort`; do
	for requested_value in $values; do
		if get_pokemon_attribute $pokemon_name $attribute | grep --quiet -c $requested_value; then 
			echo "`get_pokemon_attribute $pokemon_name Index` $pokemon_name"
			break
		fi
	done
done

#need to check if can use --quiet
#sort not nessecarilly working