#!/bin/bash

attribute=$1
requested_values=`echo $@ | cut -d " " -f 2-`

if [ "$attribute" == "T" ]; then
	attribute="Type"
else
	attribute="Weaknesses"
fi

for value in $requested_values; do
	for pokemon in `grep ^$attribute Pokemons/*/*.txt | grep $value | cut -d "/" -f 2`; do
		echo "`get_pokemon_attribute $pokemon Index` $pokemon"
	done
done | sort -nr | uniq